"""Initial migration: create all tables

Revision ID: 0ffb52e3c1b5
Revises: 
Create Date: 2026-01-14 18:39:17.793894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ffb52e3c1b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('position', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('RU', 'EN', name='language'), nullable=False),
    sa.Column('personality', sa.Enum('FRIENDLY', 'PROFESSIONAL', 'MOTIVATING', name='personality'), nullable=False),
    sa.Column('interview_type', sa.Enum('SCREENING', 'TECHNICAL', 'BEHAVIORAL', 'MIXED', name='interviewtype'), nullable=True),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.Column('share_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_organizer_id'), 'sessions', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_sessions_share_url'), 'sessions', ['share_url'], unique=True)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='interviewstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_file_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_session_id'), 'interviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('session_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role_context', sa.Text(), nullable=True),
    sa.Column('context_description', sa.Text(), nullable=True),
    sa.Column('expected_knowledge', sa.Text(), nullable=True),
    sa.Column('interaction_style', sa.String(length=50), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.Column('customer_simulation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_config_session_id'), 'session_config', ['session_id'], unique=True)
    op.create_table('session_evaluation_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('criterion_name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_evaluation_criteria_session_id'), 'session_evaluation_criteria', ['session_id'], unique=False)
    op.create_table('session_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_questions_session_id'), 'session_questions', ['session_id'], unique=False)
    op.create_table('session_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_requirements_session_id'), 'session_requirements', ['session_id'], unique=False)
    op.create_table('candidate_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'SHORTLISTED', 'REJECTED', name='candidatestatustype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_status_interview_id'), 'candidate_status', ['interview_id'], unique=True)
    op.create_index(op.f('ix_candidate_status_status'), 'candidate_status', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('readiness', sa.String(length=500), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_interview_id'), 'evaluations', ['interview_id'], unique=True)
    op.create_table('question_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('analysis_note', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answers_interview_id'), 'question_answers', ['interview_id'], unique=False)
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('scenario_type', sa.String(length=255), nullable=False),
    sa.Column('scenario_description', sa.Text(), nullable=False),
    sa.Column('client_role', sa.String(length=255), nullable=False),
    sa.Column('client_behavior', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_scenarios_interview_id'), 'simulation_scenarios', ['interview_id'], unique=True)
    op.create_table('transcript_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audio_chunk_url', sa.String(length=1000), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_messages_interview_id'), 'transcript_messages', ['interview_id'], unique=False)
    op.create_table('evaluation_improvements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('improvement_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_improvements_evaluation_id'), 'evaluation_improvements', ['evaluation_id'], unique=False)
    op.create_table('evaluation_key_phrases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('phrase_type', sa.String(length=50), nullable=False),
    sa.Column('phrase_text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_key_phrases_evaluation_id'), 'evaluation_key_phrases', ['evaluation_id'], unique=False)
    op.create_table('evaluation_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('observation_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_observations_evaluation_id'), 'evaluation_observations', ['evaluation_id'], unique=False)
    op.create_table('evaluation_strengths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('strength_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_strengths_evaluation_id'), 'evaluation_strengths', ['evaluation_id'], unique=False)
    op.create_table('simulation_dialog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['simulation_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_dialog_scenario_id'), 'simulation_dialog', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_dialog_scenario_id'), table_name='simulation_dialog')
    op.drop_table('simulation_dialog')
    op.drop_index(op.f('ix_evaluation_strengths_evaluation_id'), table_name='evaluation_strengths')
    op.drop_table('evaluation_strengths')
    op.drop_index(op.f('ix_evaluation_observations_evaluation_id'), table_name='evaluation_observations')
    op.drop_table('evaluation_observations')
    op.drop_index(op.f('ix_evaluation_key_phrases_evaluation_id'), table_name='evaluation_key_phrases')
    op.drop_table('evaluation_key_phrases')
    op.drop_index(op.f('ix_evaluation_improvements_evaluation_id'), table_name='evaluation_improvements')
    op.drop_table('evaluation_improvements')
    op.drop_index(op.f('ix_transcript_messages_interview_id'), table_name='transcript_messages')
    op.drop_table('transcript_messages')
    op.drop_index(op.f('ix_simulation_scenarios_interview_id'), table_name='simulation_scenarios')
    op.drop_table('simulation_scenarios')
    op.drop_index(op.f('ix_question_answers_interview_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_evaluations_interview_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_candidate_status_status'), table_name='candidate_status')
    op.drop_index(op.f('ix_candidate_status_interview_id'), table_name='candidate_status')
    op.drop_table('candidate_status')
    op.drop_index(op.f('ix_session_requirements_session_id'), table_name='session_requirements')
    op.drop_table('session_requirements')
    op.drop_index(op.f('ix_session_questions_session_id'), table_name='session_questions')
    op.drop_table('session_questions')
    op.drop_index(op.f('ix_session_evaluation_criteria_session_id'), table_name='session_evaluation_criteria')
    op.drop_table('session_evaluation_criteria')
    op.drop_index(op.f('ix_session_config_session_id'), table_name='session_config')
    op.drop_table('session_config')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_session_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_sessions_share_url'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organizer_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

