"""add_parent_question_id_and_allow_dynamic_questions

Revision ID: ccce7912d7cc
Revises: 0ffb52e3c1b5
Create Date: 2026-01-17 20:22:07.107261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccce7912d7cc'
down_revision = '0ffb52e3c1b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_config', sa.Column('allow_dynamic_questions', sa.Boolean(), nullable=True))
    op.add_column('session_questions', sa.Column('parent_question_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_session_questions_parent_question_id'), 'session_questions', ['parent_question_id'], unique=False)
    op.create_foreign_key(None, 'session_questions', 'session_questions', ['parent_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_questions', type_='foreignkey')
    op.drop_index(op.f('ix_session_questions_parent_question_id'), table_name='session_questions')
    op.drop_column('session_questions', 'parent_question_id')
    op.drop_column('session_config', 'allow_dynamic_questions')
    # ### end Alembic commands ###

